---
- name: Remove and create logs dir
  file: path={{ logs_dir | default(ansible_env.HOME) }}/logs/ state={{ item }}
  with_items:
    - absent
    - directory

- name: Load octario configuration
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ playbook_dir }}/../octario.cfg"
    - "{{ inventory_dir }}/octario.cfg"
    - "/etc/octario.cfg"

# This is optional since not every component must have common configuration across all releases
- name: Load component common configuration
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - "{{ playbook_dir }}/../components_config/common/{{ component.name }}.cfg"
    - "{{ inventory_dir }}/components_config/common/{{ component.name }}.cfg"

- name: Load component configuration by specific relaease
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ playbook_dir }}/../components_config/{{ component.version | default(rhos_default_version) }}/{{ component.name }}/component.cfg"
    - "{{ inventory_dir }}/components_config/{{ component.version | default(rhos_default_version) }}/{{ component.name }}/component.cfg"
    - "{{ component.path | default(inventory_dir + '/' + component.name) }}/{{ component.config_file_name | default(config_file_name) }}"
    - "{{ playbook_dir }}/../component.cfg"
    - "{{ inventory_dir }}/component.cfg"
    - "/etc/component.cfg"
    - "{{ component.path | default(inventory_dir + '/' + component.name) }}/jenkins-config.yml"
    - "{{ playbook_dir }}/../jenkins-config.yml"
    - "{{ inventory_dir }}/jenkins-config.yml"
    - "/etc/jenkins-config.yml"

- name: Setup component configuration based on operating system
  set_fact:
    component_config="{{ test_config.virt[item] | default(omit) }}"
  with_items:
    - "default"
    - "{{ ansible_os_family }}-{{ ansible_distribution_version | int }}"
    - "{{ ansible_os_family }}-{{ ansible_distribution_version }}"

- name: Copy component to remote host
  synchronize:
    src="{{ item }}"
    dest="{{ ansible_env.HOME }}"
  with_first_found:
    - "{{ component.path | default(omit) }}"
    - "{{ inventory_dir }}/{{ component.name }}"
    - "{{ inventory_dir }}/../{{ component.name }}"
    - "{{ playbook_dir }}/../{{ component.name }}"
