# The number of workers to use, defaults to the number of CPUs
- name: Run Tempest - rpm
  shell: "ostestr -s --no-pretty --regex '{{ tempest_regex | default('') }}' ./skipfile | subunit2junitxml --output-to=tempest.xml | subunit2pyunit"
  ignore_errors: true
  args:
    chdir: tempest
  tags:
    - skip_ansible_lint
