# This file is used by the jenkins job

# (migi) flake8 is added to tox.ini for removing ugly warning:
#        WARNING:test command found but not installed in testenv
#
# (migi) to keep track of exact packages from outside of rhelosp repo
#        all deps from copr are listed, even if those were dependency
#        requirements from other packages being installed
#
#        dependencies with explicit versions are provided by the
#        copr repository.
pep8:

    rpm_deps: [
      python-hacking-0.10.2
    ]

    remove_rpm: []

    run:
        sed -i '/whitelist_externals = find/a\\tflake8' tox.ini;
        tox --sitepackages -v -e pep8 2>&1 | tee ../logs/testrun.log;


# (migi) python-novaclient is installed and then removed to satisfy
#        all runtime dependencies for the nova component.
#
unittest:

    rpm_deps: [
      python-novaclient,
      python-linecache2-1.0.0,
      python-testtools-1.8.0,
      python-traceback2-1.4.0,
      python-unittest2-1.0.1,
      python-subunit,
      python-testrepository,
      python-tempest-lib,
      python-mock,
      python-testscenarios-0.4,
      python-requests-mock
    ]

    remove_rpm: [
      python-novaclient
    ]

    run:
        tox --sitepackages -v -e py27 2>&1 | tee ../logs/testrun.log;


# Common rpm deps needed for all tester types (pep8 / unittest)
#
rpm_deps: [
    git,
    python-virtualenv,
    python-pbr,
    python-pep8,
    python-flake8,
    python-tox-2.1.1,
    "{{ hostvars[inventory_hostname][tester.component.tox_target]['rpm_deps'] }}"
]


# The rpms that shouldn't be installed when running tests
remove_rpm: [
    "{{ hostvars[inventory_hostname][tester.component.tox_target]['remove_rpm'] }}"
]


# (N.B.) We truncate *requirements.txt to ensure we're only using installed
#        non-test packages.
#
#        We remove install_command from tox.ini because it force
#        upgrades everything, regardless of --sitepackages.
nova_virt_run_config:

  run: >
      set -o pipefail;
      rpm -qa | sort > ../logs/installed-rpms.log;
      truncate --size 0 requirements.txt;
      truncate --size 0 test-requirements.txt;
      sed -i "s/^install_command\s*=.*$//" tox.ini;
      {{ hostvars[inventory_hostname][tester.component.tox_target]['run'] }}


# NOTE: This is the main section. It must exist.
test_config:
  virt:
    RedHat-7:
      setup:
        install: "{{rpm_deps}}"
        remove: "{{remove_rpm}}"
      run: "{{nova_virt_run_config.run}}"
